name: Dev workflow
on:
  push:
    branches:
      - dev
    paths:
      - 'pypong/**'
      - '.github/workflows/dev-workflow.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: cd pypong && pytest
